//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Model
{
    public partial class Contact
    {
        public Contact()
        {
            this.ContactGroups = new HashSet<ContactGroup>();
        }
    
        public long Id { get; set; }
        public string Email { get; set; }
        public string Name { get; set; }
        public long UserId { get; set; }
    
        public virtual User User { get; set; }
        public virtual ICollection<ContactGroup> ContactGroups { get; set; }
    }
    
}
